import {describe,expect,test} from 'bun:test';
import {createAIResearchPlanner,resolveCodes,inferIntent,planResearch,ResearchOrchestrator} from '../src/worker/orchestrator';
import type {ResearchRetriever,EvidenceBundle,RetrievedSection,RelationshipEdge,HistoryEvent} from '../src/worker/retrieval';
const s=(uid:string,c:string):RetrievedSection=>({uid,lawCode:c,sectionNum:'1',citation:{label:`${c} § 1`,lawCode:c,sectionNum:'1',url:''},text:c,relevance:1,matchType:'fulltext'});
class Fake implements ResearchRetriever{async search(x:{query:string;code?:string}):Promise<EvidenceBundle>{const c=x.code||'FAM';return{query:x.query,results:[s(c+':1',c)],relationships:[],retrieval:{methods:['full-text'],complete:true}}}async getSection(){return null}async getRelationships(uid:string):Promise<RelationshipEdge[]>{return[{sourceUid:uid,targetUid:'GOV:2',relationship:'references',confidence:1}]}async getHistory(uid:string):Promise<HistoryEvent[]>{return[{id:uid,uid,eventType:'amended'}]}}

test('resolves codes and keeps deterministic fallback bounded',()=>{expect(resolveCodes('Family Code and Government Code')).toEqual(['FAM','GOV']);expect(inferIntent('what do they have in common?',['FAM','GOV'])).toBe('compare');expect(planResearch('Family Code and Government Code have in common').steps.length).toBe(1)});
test('accepts an AI-selected plan and executes its operations',async()=>{const planner={plan:async()=>({intent:'compare' as const,codes:['FAM','GOV'],subjects:['Family Code','Government Code'],steps:[{operation:'search' as const,args:{query:'shared custody',limit:2},reason:'Find responsive provisions.'},{operation:'relationships' as const,args:{depth:1},reason:'Trace explicit references.'}]})};const r=await new ResearchOrchestrator(new Fake(),planner).research('What do Family Code and Government Code have in common?');expect(r.state.codes).toEqual(['FAM','GOV']);expect(r.state.plan).toHaveLength(2);expect(r.state.findings.length).toBeGreaterThan(1);expect(r.state.relationships.length).toBeGreaterThan(0)});
test('normalizes planner JSON through the provider boundary',async()=>{const planner=createAIResearchPlanner({generate:async()=>JSON.stringify({intent:'lookup',codes:['GOV','not-a-code'],subjects:['Government Code'],steps:[{operation:'search',args:{query:'GOV section 1',limit:99},reason:'Exact authority'}]})});const plan=await planner.plan('What does Government Code section 1 say?');expect(plan.codes).toEqual(['GOV']);expect(plan.steps[0].args.limit).toBe(20)});

test('orchestrates evidence with the fallback plan',async()=>{const r=await new ResearchOrchestrator(new Fake()).research('What do Family Code and Government Code have in common?');expect(r.state.findings.length).toBeGreaterThan(0);expect(r.state.relationships.length).toBeGreaterThan(0)});
