import type { EvidenceBundle, HistoryEvent, RelationshipEdge, RetrievedSection, ResearchRetriever } from './retrieval';
export type ResearchIntent='lookup'|'explain'|'compare'|'investigate'|'chronology'|'synthesis';
export interface ResearchState{question:string;intent:ResearchIntent;codes:string[];subjects:string[];findings:RetrievedSection[];relationships:RelationshipEdge[];history:HistoryEvent[];unresolved:string[];methods:string[]}
export interface ResearchPlan{intent:ResearchIntent;codes:string[];subjects:string[];steps:{operation:'search'|'history';args:Record<string,unknown>;reason:string}[]}
export interface ResearchResult{state:ResearchState;evidence:EvidenceBundle;prompt:string}
export interface TextGenerationProvider{generate(input:{system:string;user:string;messages?:Array<{role:'system'|'user'|'assistant';content:string}>}):Promise<string>}
const CODES:Record<string,string>={BPC:'Business and Professions Code',CIV:'Civil Code',CCP:'Code of Civil Procedure',PEN:'Penal Code',WIC:'Welfare and Institutions Code',EVID:'Evidence Code',CONS:'California Constitution',EDC:'Education Code',HSC:'Health and Safety Code',LAB:'Labor Code',PROB:'Probate Code',GOV:'Government Code',FAM:'Family Code',VEH:'Vehicle Code',PCC:'Public Contract Code'};
const aliases:Record<string,string>={...Object.fromEntries(Object.entries(CODES).flatMap(([k,v])=>[[k.toLowerCase(),k],[v.toLowerCase(),k]])),'fam. code':'FAM','fam code':'FAM','gov. code':'GOV','gov code':'GOV','family':'FAM','government':'GOV','california constitution':'CONS'};
const clean=(s:string)=>s.trim().replace(/\s+/g,' ');
export function resolveCodes(q:string){const found=new Set<string>(),x=q.toLowerCase();for(const[a,c]of Object.entries(aliases))if(x.includes(a))found.add(c);return[...found]}
export function inferIntent(q:string,codes:string[]):ResearchIntent{const x=q.toLowerCase();if(/\b(compare|difference|versus|\bvs\.?\b|same|common|overlap|similar)\b/.test(x)||codes.length>1)return'compare';if(/\b(history|historical|changed|amended|effective|before|after)\b/.test(x))return'chronology';if(/\b(why|how|relationship|relate|connect|exception|subject to|depends on)\b/.test(x))return'investigate';if(/\b(what is|what are|explain|define)\b/.test(x))return'explain';if(/\b(section|§)\b/.test(x))return'lookup';return'synthesis'}
const probes=['definition','court','agency','authority','proceeding','records','enforcement'];
export function planResearch(question:string):ResearchPlan{const q=clean(question),codes=resolveCodes(q),intent=inferIntent(q,codes),steps:ResearchPlan['steps']=[];if(codes.length>=2&&intent==='compare')for(const code of codes.slice(0,4))for(const probe of probes)steps.push({operation:'search',args:{query:probe,code,limit:5},reason:`Compare ${probe} evidence in ${CODES[code]??code}.`});else steps.push({operation:'search',args:{query:q,limit:12},reason:'Retrieve responsive primary provisions.'});if(/\b(history|historical|changed|amended|effective)\b/i.test(q))steps.push({operation:'history',args:{limit:50},reason:'Retrieve temporal evidence.'});return{intent,codes,subjects:codes.map(c=>CODES[c]??c),steps:steps.slice(0,60)}}
export class ResearchOrchestrator{constructor(private readonly retriever:ResearchRetriever,private readonly limits={sections:50,relationships:100,history:100}){}async research(question:string):Promise<ResearchResult>{const plan=planResearch(question),f=new Map<string,RetrievedSection>(),r=new Map<string,RelationshipEdge>(),h=new Map<string,HistoryEvent>(),methods=new Set<string>(),unresolved:string[]=[];for(const step of plan.steps){try{if(step.operation==='search'){const e=await this.retriever.search(step.args as {query:string;code?:string;limit?:number});e.results.forEach(x=>f.set(x.uid,x));e.retrieval.methods.forEach(x=>methods.add(x))}else for(const uid of [...f.keys()].slice(0,this.limits.history)){const es=await this.retriever.getHistory(uid,step.args as never);es.forEach(x=>h.set(x.id,x))}}catch(e){unresolved.push(`${step.operation}: ${e instanceof Error?e.message:String(e)}`)}}for(const s of [...f.values()].slice(0,this.limits.sections)){if(r.size>=this.limits.relationships)break;try{const es=await this.retriever.getRelationships(s.uid,{direction:'both',depth:1,limit:8});es.forEach(e=>r.set(`${e.sourceUid}|${e.targetUid}|${e.relationship}|${e.referenceText??''}`,e))}catch(e){unresolved.push(`relationships ${s.uid}: ${e instanceof Error?e.message:String(e)}`)}}if(!f.size)unresolved.push('No primary statutory provisions were retrieved.');const state:ResearchState={question:clean(question),intent:plan.intent,codes:plan.codes,subjects:plan.subjects,findings:[...f.values()].slice(0,this.limits.sections),relationships:[...r.values()].slice(0,this.limits.relationships),history:[...h.values()].slice(0,this.limits.history),unresolved,methods:[...methods]};const evidence:EvidenceBundle={query:state.question,results:state.findings,relationships:state.relationships,retrieval:{methods:state.methods,complete:!unresolved.length}};return{state,evidence,prompt:JSON.stringify({question:state.question,intent:state.intent,subjects:state.subjects,authorities:state.findings.map(s=>({uid:s.uid,citation:s.citation,code:s.lawCode,section:s.sectionNum,title:s.title,text:s.text,history:s.history,validFrom:s.validFrom,validTo:s.validTo})),relationships:state.relationships,history:state.history,unresolved:state.unresolved})}}}
export const ORCHESTRATOR_SYSTEM_PROMPT=`You are the primary-source research engine for California Legislative Information. You are not a generic chatbot. Reason over the supplied California statutory provisions before answering. Never invent citations, sections, relationships, legislative intent, history, procedural facts, or quotations. Every substantive legal proposition must be traceable to a supplied citation. Distinguish statutory text, direct textual comparison, and inference. If evidence is insufficient, say what is missing instead of using memory. For multi-turn conversations, use prior messages for context but re-ground new legal propositions in the corpus. Answer with: Short answer; Evidence and commonalities; Statutory connections; Analysis; Limits; Sources.`;
export async function generateResearchAnswer(o:ResearchOrchestrator,p:TextGenerationProvider,q:string,messages:Array<{role:'user'|'assistant';content:string}>=[]){const x=await o.research(q);return{state:x.state,answer:await p.generate({system:ORCHESTRATOR_SYSTEM_PROMPT,messages:[{role:'system',content:ORCHESTRATOR_SYSTEM_PROMPT},...messages.slice(-8),{role:'user',content:`CORPUS EVIDENCE:\n${x.prompt}\n\nCURRENT QUESTION:\n${q}`}],user:x.prompt})}}
export function createCloudflareAIProvider(ai:{run:(model:string,input:unknown)=>Promise<unknown>},model='@cf/meta/llama-3.1-8b-instruct-fast'):TextGenerationProvider{return{async generate(input){const out=await ai.run(model,{messages:input.messages??[{role:'system',content:input.system},{role:'user',content:input.user}],temperature:0.1,max_tokens:1400}) as {response?:unknown};if(typeof out.response!=='string'||!out.response.trim())throw new Error('AI generation returned no answer.');return out.response.trim()}}}
