import { D1ResearchRetriever } from './worker/retrieval';
import { ResearchOrchestrator, createCloudflareAIProvider, generateResearchAnswer } from './worker/orchestrator';
import type { D1Database } from './worker/retrieval';
interface AI { run(model:string,input:unknown):Promise<unknown>; }
interface Env { ASSETS:Fetcher; R2:R2Bucket; LEGINFO_DB?:D1Database; AI?:AI; AI_MODEL?:string; AI_SEARCH_ENDPOINT?:string; }
const DEFAULT_AI_SEARCH_ENDPOINT='https://5f679b75-e58c-4cbd-8350-b2c83df8f361.search.ai.cloudflare.com/chat/completions';
const MAX_QUERY_LENGTH=1000;
const cors=():HeadersInit=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...cors()}});
async function research(request:Request,env:Env){const body=await request.json().catch(()=>null) as {query?:unknown}|null;if(typeof body?.query!=='string'||!body.query.trim())return json({error:'A research question is required.'},400);if(body.query.length>MAX_QUERY_LENGTH)return json({error:'Research question is too long.'},413);try{if(env.LEGINFO_DB){const o=new ResearchOrchestrator(new D1ResearchRetriever(env.LEGINFO_DB));if(!env.AI)return json(await o.research(body.query));return json(await generateResearchAnswer(o,createCloudflareAIProvider(env.AI,env.AI_MODEL),body.query));}return await aiSearch(request,env);}catch(e){return json({error:e instanceof Error?e.message:'Research failed.'},502);}}
async function search(request:Request,env:Env){if(!env.LEGINFO_DB)return json({error:'Legislative retrieval is not configured.'},503);const body=await request.json().catch(()=>null) as {query?:unknown;code?:string;limit?:number;exactUid?:string}|null;if(typeof body?.query!=='string')return json({error:'A search query is required.'},400);try{return json(await new D1ResearchRetriever(env.LEGINFO_DB).search(body));}catch(e){return json({error:e instanceof Error?e.message:'Legislative retrieval failed.'},400);}}
async function aiSearch(request:Request,env:Env){const body=await request.json().catch(()=>null) as {query?:string}|null;const query=body?.query?.trim()||'';if(!query)return json({error:'A search question is required.'},400);const upstream=await fetch(env.AI_SEARCH_ENDPOINT||DEFAULT_AI_SEARCH_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:query}]})});return new Response(await upstream.text(),{status:upstream.status,headers:{'content-type':upstream.headers.get('content-type')||'application/json',...cors()}});}
export default{async fetch(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{headers:cors()});const p=new URL(request.url).pathname;if(p==='/api/research'&&request.method==='POST')return research(request,env);if(p==='/api/search'&&request.method==='POST')return search(request,env);if(p==='/api/answer'&&request.method==='POST')try{return await aiSearch(request,env);}catch(e){return json({error:e instanceof Error?e.message:'AI Search unavailable.'},502);}if(p==='/api/health'&&request.method==='GET')return json({ok:true,service:'leginfo',retrieval:Boolean(env.LEGINFO_DB),research:Boolean(env.LEGINFO_DB),ai:Boolean(env.AI)});return env.ASSETS.fetch(request);}};
