import { StaticCorpusRetriever } from './worker/static-retrieval';
import { ResearchOrchestrator, createCloudflareAIProvider, generateResearchAnswer } from './worker/orchestrator';
interface AI { run(model:string,input:unknown):Promise<unknown>; }
interface Env { ASSETS:Fetcher; R2:R2Bucket; AI?:AI; AI_MODEL?:string; AI_SEARCH_ENDPOINT?:string; }
const DEFAULT_AI_SEARCH_ENDPOINT='https://5f679b75-e58c-4cbd-8350-b2c83df8f361.search.ai.cloudflare.com/chat/completions';
const MAX_QUERY_LENGTH=1000;
const cors=():HeadersInit=>({'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'});
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...cors()}});
function retriever(request:Request,env:Env){return new StaticCorpusRetriever(env.ASSETS,new URL(request.url));}
async function research(request:Request,env:Env){const body=await request.json().catch(()=>null) as {query?:unknown}|null;if(typeof body?.query!=='string'||!body.query.trim())return json({error:'A research question is required.'},400);if(body.query.length>MAX_QUERY_LENGTH)return json({error:'Research question is too long.'},413);try{const o=new ResearchOrchestrator(retriever(request,env));if(env.AI)return json(await generateResearchAnswer(o,createCloudflareAIProvider(env.AI,env.AI_MODEL),body.query.trim()));const result=await o.research(body.query.trim());return json({answer:'Primary-source evidence retrieved from the California legislative corpus.',state:result.state,evidence:result.evidence});}catch(e){return json({error:e instanceof Error?e.message:'Research failed.'},502);}}
async function search(request:Request,env:Env){const body=await request.json().catch(()=>null) as {query?:unknown;code?:string;limit?:number;exactUid?:string}|null;if(typeof body?.query!=='string'||!body.query.trim())return json({error:'A search query is required.'},400);try{return json(await retriever(request,env).search(body));}catch(e){return json({error:e instanceof Error?e.message:'Legislative retrieval failed.'},400);}}
async function aiSearch(request:Request,env:Env){const body=await request.json().catch(()=>null) as {query?:string}|null;const query=body?.query?.trim()||'';if(!query)return json({error:'A research question is required.'},400);const upstream=await fetch(env.AI_SEARCH_ENDPOINT||DEFAULT_AI_SEARCH_ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:query}]})});return new Response(await upstream.text(),{status:upstream.status,headers:{'content-type':upstream.headers.get('content-type')||'application/json',...cors()}});}
export default{async fetch(request:Request,env:Env){if(request.method==='OPTIONS')return new Response(null,{headers:cors()});const p=new URL(request.url).pathname;if(p==='/api/research'&&request.method==='POST')return research(request,env);if(p==='/api/search'&&request.method==='POST')return search(request,env);if(p==='/api/answer'&&request.method==='POST')return aiSearch(request,env);if(p==='/api/health'&&request.method==='GET')return json({ok:true,service:'leginfo',retrieval:'static-corpus',research:true,ai:Boolean(env.AI)});return env.ASSETS.fetch(request);}};
